//------------------------------------------------------------------------
//  D O     N O T     E D I T     T H I S     F I L E
//------------------------------------------------------------------------
// File         :  cbi_pkt_tables_a.h
// Date Created :  Fri Sep 14 14:07:50 2012
//
// Description  : This file was automatically generated by the BIParser.
//                It provides packet address table and packet size table
//                initialization code as well as an instrument memory
//                usage summary for the communication data structures.
//------------------------------------------------------------------------


//-----------------------------------------------------------------------+
//  The following provides for C++ compatibility (ie, C++ routines can   |
//  explicitly use this include file).                                   |
//-----------------------------------------------------------------------+
#if defined (__cplusplus)
extern "C" {
#endif


// System
#include <defts101.h>
// Core
#include "dig_board_6048-113.h"
#include "cbi_core_inst_includes.h"
#include "cbi_commstructs_a.h"
//Local
#include "cbi_tags_a.h"
//==================================================================================
// Memory usage for communication data structures:
//
// Structure           Element tally                             Mem (words)  # X-Pkts 
//==================================================================================
// cbi_cmd             : (3 + 4)                                       = 7      1
// cbi_stat            : (3 + 15)                                      = 18     1
// cbi_debug           : (2 + 660 + 660)                               = 1322   661
// cbi_ident           : (3 + 16 * 0.25 + 28 * 0.25 + 4)               = 18.0   1.0
// cbi_heartbeat       : (3)                                           = 3      1
// cbi_module_config   : (9 + 44 * 0.25)                               = 20.0   1.0
//                                                           -----------------------
//                                                            TOTAL : 1388.0
//==================================================================================


int init_core_packet_tables() {
   //-------------------------------------------------------+
   // Packet address table initialization                   |
   //-------------------------------------------------------+
   *(p_pkt_adr_table + CBI_CMD_TAG)                     = (int)&INST_cmd            + CBI_MPS_OFFSET;
   *(p_pkt_adr_table + CBI_STAT_TAG)                    = (int)&INST_stat           + CBI_MPS_OFFSET;
   *(p_pkt_adr_table + CBI_DEBUG_TAG)                   = (int)&INST_debug          + CBI_MPS_OFFSET;
   *(p_pkt_adr_table + CBI_IDENT_TAG)                   = (int)&INST_ident          + CBI_MPS_OFFSET;
   *(p_pkt_adr_table + CBI_HEARTBEAT_TAG)               = (int)&INST_heartbeat      + CBI_MPS_OFFSET;
   *(p_pkt_adr_table + CBI_MODULE_CONFIG_TAG)           = (int)&INST_module_config  + CBI_MPS_OFFSET;
   //-------------------------------------------------------+
   // Packet size table initialization                      |
   //-------------------------------------------------------+
   *(p_pkt_siz_table + CBI_CMD_TAG)                     = sizeof(INST_cmd);         
   *(p_pkt_siz_table + CBI_STAT_TAG)                    = sizeof(INST_stat);        
   *(p_pkt_siz_table + CBI_DEBUG_TAG)                   = 2;
   *(p_pkt_siz_table + CBI_IDENT_TAG)                   = sizeof(INST_ident);       
   *(p_pkt_siz_table + CBI_HEARTBEAT_TAG)               = sizeof(INST_heartbeat);   
   *(p_pkt_siz_table + CBI_MODULE_CONFIG_TAG)           = sizeof(INST_module_config);

  return CBI_F_SUCCESS;
}
