//------------------------------------------------------------------------
//  D O     N O T     E D I T     T H I S     F I L E
//------------------------------------------------------------------------
// File         :  CBI_protos_a.h
// Date Created :  Fri Apr  9 15:45:47 2010
// Input File   :  cbi_core_communication_structs.def
//
// Description  : This file was automatically generated by the BIParser.
//                It contains C prototypes for the custom datatype conversion
//                functions that were generated for derived typedefs.
//----------------------------------------------------------------------------
#ifndef CBI_protos_A_H
#define CBI_protos_A_H

int cbi_init_a(CBI_CTL_MODULE*);


#endif
