#ifndef CBI_TAGS_A_H 
#define CBI_TAGS_A_H 

//------------------------------------------------------------------------
//  D O     N O T     E D I T     T H I S     F I L E
//------------------------------------------------------------------------
// File         :  cbi_tags_a.h 
// Date Created :  Fri Sep 14 14:07:50 2012
//
// Description  :  This file was automatically generated by the BIParser.
//                 It defines a unique tag ID # for each of the
//                 communication data structures employed for the given
//                 platform(s).
//                 This tag ID # is what is used as an index into the 
//                 instrument's on-board packet size/packet address tables
//                 for FPGA-mediated structure addressing.  It is also
//                 used to allow the user, within control system code, to 
//                 indicate which structure should be transferred during a
//                 cbi_gp_struct() READ/WRITE operation.
//------------------------------------------------------------------------

#include "cbi_core_inst_includes.h" 


//================================================================
enum CBI_TAG_ENUM {
  CBI_ILLEGAL_TAG,
  CBI_CMD_TAG,
  CBI_STAT_TAG,
  CBI_DEBUG_TAG,
  CBI_IDENT_TAG,
  CBI_HEARTBEAT_TAG,
  CBI_MODULE_CONFIG_TAG,
  CBI_FIRST_LOCAL_TAG
};

//------------------------------------------------------
// Define the total number of platform-specific
// communication structures
//------------------------------------------------------
#define TOT_CBI_COMM_STRUCTS          6



#endif
