#ifndef CBI_TYPES_A_H
#define CBI_TYPES_A_H

//------------------------------------------------------------------------
//  D O     N O T     E D I T     T H I S     F I L E
//------------------------------------------------------------------------
// File         :  cbi_types_a.h
// Date Created :  Fri Sep 14 14:07:50 2012
//
// Description  :  This file was automatically generated by the BIParser.
//                 It defines the collection of communication data 
//                 structures available for the given platform(s).
//------------------------------------------------------------------------
//
//-----------------------------------------------------------------------+
//  The following provides for C++ compatibility (ie, C++ routines can   |
//  explicitly use this include file).                                   |
//-----------------------------------------------------------------------+
#if defined (__cplusplus)
extern "C" {
#endif


#define CBI_COMM_STRUCT_REV  1209141407

//-----------------------------------------------------------------------+
// Set CONTROL SYSTEM flag                                               |
//-----------------------------------------------------------------------+
#if defined (CESR_VMS) || defined(CESR_UNIX)
#define INST_CONTROL
#if defined(INST_COMMUNICATIONS)
#define INST_DEFINE_CONFIG
#endif
#endif

#include "cbi_constants.h" 
//================================================================


typedef struct {
      int cmd;
      int cmd_status;
      int error[CBI_MAX_ERROR_WORDS];
      int handshake;
} CBI_CMD;



typedef struct {
      int state;
      int status;
      int num_levels;
      int trace[CBI_MAX_TRACE_LEVELS];
} CBI_STAT;



typedef struct {
      int write_ptr;
      int debug[CBI_MAX_DEBUG_WORDS];
      int routine[CBI_MAX_DEBUG_WORDS];
      int padding;
} CBI_DEBUG;



//-----------------------------------------------------------------------+
// IDENT   - Strucuture to hold TigerSHARC BPM-specific                  |
//           instrument-managed BPM identification and addressing        |
//           information.                                                |
//           This is the platform-specific counterpart to the more       |
//           more general global structure called CBI_IDENT  common to   |
//           all CBI instruments.                                        |
//                                                                       |
//                                                                       |
// ipaddr     : IP address of the BPM                                    |
//              TODO: Accomodate proper string.                          |
//                                                                       |
// hostname   : Hostname of the BPM  (Serves as a unique global          |
//              identifier for the instrument.)                          |
//              TODO: accomodate proper string.                          |
//                                                                       |
// module_type:                                                          |
//                                                                       |
// fpga_maj   : Major version number of digital board FPGA firmware.     |
//                                                                       |
// fpga_min   : Minor version number of digital board FPGA firmware.     |
//                                                                       |
// fpga_id    : FPGA firmware version numbers for each front-end board.  |
//-----------------------------------------------------------------------+
typedef struct {
      char ipaddr[16];
      char hostname[28];
      int module_type;
      int fpga_maj;
      int fpga_min;
      int fe_fpga_id[4];
} CBI_IDENT;



//-----------------------------------------------------------------------+
// HEARTBEAT  -   Holds DSP activity and timing integrity status values  |
//                                                                       |
//                                                                       |
// DSP_heartbeat    : Holds a wrapping counter that will always be       |
//                    incrementing if the DSP's software is operating    |
//                    correctly.                                         |
//                                                                       |
// timing_integrity : A bit pattern that shows the status of the timing  |
//                    signal over the last X seconds.  Each bit          |
//                    to a one-second assessment interval.  High bits    |
//                    indicate that the number of turns markers seen by  |
//                    the instrument in the corresponding one second     |
//                    interval was within the thresholds for adequate    |
//                    timing signal availability.                        |
//                    This word is only accurate if the DSP_heartbeat    |
//                    above is also incrementing.                        |
//                                                                       |
// turns_seen       : Number of turns markers seen in the sampling period|
//-----------------------------------------------------------------------+
typedef struct {
      int heartbeat;
      int timing_integrity;
      int turns_seen;
} CBI_HEARTBEAT;



//-----------------------------------------------------------------------+
// MODULE_CONFIG - Holds read-only information types that are common to  |
//                 ALL instrumentation units that use BeamInstSupport.   |
//                 Certain values are meant to be encoded in the DSP     |
//                 executable at COMPILE TIME and define characteristics |
//                 of a given build, while the rest define               |
//                 hardware-specific values that get polled and          |
//                 published during DSP initialization.                  |
//                                                                       |
// Control System PROTECTION - READ_ONLY                                 |
//                                                                       |
// code_version     : version number of the code library used to build   |
//                    the currently running DSP executable               |
// ana_card_id      : analog card ID                                     |
// tim_card_id      : timing card ID                                     |
// dig_card_id      : digital card ID                                    |
// exe_type         : executable type running in DSP (NOTE:  multiple    |
//                    executables are available for download to the DSPs |
//                    depending on what measurements are needed          |
// exe_version      : version number associated with the specific exe    |
//                    being run in the DSP                               |
//-----------------------------------------------------------------------+
typedef struct {
      int   exe_type;
      float exe_version;
      char   ldr_name[44];
      int   build_timestamp;
      int   core_comm_struct_rev;
      int   platform_comm_struct_rev;
      int   compiler_ver;
      float lib_version;    // was code_version. Version of LIBRARY used to build DSP code?
      int   hardware_ver;
      int   firmware_ver;  // For central FPGA (Charlie's)
} CBI_MODULE_CONFIG;

typedef struct {
      CBI_CMD                         cbi_cmd;
      CBI_STAT                        cbi_stat;
      CBI_DEBUG                       cbi_debug;
      CBI_IDENT                       cbi_ident;
      CBI_HEARTBEAT                   cbi_heartbeat;
      CBI_MODULE_CONFIG               cbi_module_config;
} CBI_DATA;

#if defined (__cplusplus)
}
#endif


#endif //...types_H
